// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4xmjdo1iSRXXJY8PkthxQRhCsLe0JjIw',
    appId: '1:1038720531602:web:54ab678ca61a961d36ba4b',
    messagingSenderId: '1038720531602',
    projectId: 'noxblog-22069',
    authDomain: 'noxblog-22069.firebaseapp.com',
    storageBucket: 'noxblog-22069.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRnfa_hJyg2EGI61Is3XI1YPPzDqHspOI',
    appId: '1:1038720531602:android:98f6888b2507077e36ba4b',
    messagingSenderId: '1038720531602',
    projectId: 'noxblog-22069',
    storageBucket: 'noxblog-22069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzdOePLKO5RMkFD6zj1NHkFE8oWxeDnE',
    appId: '1:1038720531602:ios:f9a0b7404c0f9e4f36ba4b',
    messagingSenderId: '1038720531602',
    projectId: 'noxblog-22069',
    storageBucket: 'noxblog-22069.appspot.com',
    androidClientId: '1038720531602-70l3h66ro0otinvpn78ff93ajkhh7viq.apps.googleusercontent.com',
    iosClientId: '1038720531602-jfmsh1o45qdjjlhq1rbfulhc7n8ekrj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.noxblog',
  );

}